version: 2
jobs:
  build:
    machine: true
    working_directory: ~/tcnative
    steps:
      - checkout
      - run:
          name: Build netty tcnative for various platforms
          command: |
            set -x
            ./build.sh
      - store_artifacts:
          path: fedora/binaries/gen
          destination: fedora
      - store_artifacts:
          path: non-fedora/binaries/gen
          destination: non-fedora
      - store_artifacts:
          path: alpine/binaries/gen
          destination: alpine


