version: 2
jobs:
  build:
    machine: true
    working_directory: ~/tcnative
    steps:
      - checkout
      - run:
          name: Build netty tcnative for various platforms
          command: ./build.sh
      #- store_artifacts:
      #    path: fedora/binaries/gen
      #    destination: fedora
      - store_artifacts:
          path: /output/gen/netty-tcnative/openssl-static/target/netty-tcnative-openssl-static-2.0.8.Final-SNAPSHOT-linux-x86_64.jar
          destination: non-fedora
      #- store_artifacts:
      #    path: alpine/binaries/gen
      #    destination: alpine
